name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (used for name of the release)."
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBUILD
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild .\DWMEnableMMCSS.sln -t:rebuild -verbosity:diag -p:Configuration=Release -p:Platform=x64

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: v${{inputs.version}}
          tag: ${{inputs.version}}
          artifacts: ./x64/Release/DWMEnableMMCSS.exe
